# Generated by Django 3.2.9 on 2022-01-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warcaby_game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='id',
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='guest_player',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='room_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
