# Generated by Django 3.2.9 on 2022-01-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warcaby_game', '0003_auto_20220124_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='countdown_started',
            field=models.BooleanField(default=False),
        ),
    ]
