# Generated by Django 3.2.9 on 2022-01-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warcaby_game', '0004_gameroom_countdown_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='countdown_started',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='guest_ready',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='host_ready',
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='game_state',
            field=models.CharField(choices=[('L', 'In lobby'), ('P', 'In game')], max_length=1),
        ),
    ]
