# Generated by Django 3.2.9 on 2022-01-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warcaby_game', '0005_auto_20220124_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='game_state',
            field=models.CharField(choices=[('L', 'In lobby'), ('P', 'In game'), ('O', 'Game over')], max_length=1),
        ),
    ]
